# Generated by Django 2.2.12 on 2021-04-24 21:18

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('mark_per_match', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/team/log')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.IntegerField(db_index=True)),
                ('status', models.BooleanField()),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('mark_per_match', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/players/logo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('team_a_state', jsonfield.fields.JSONField(default=dict)),
                ('team_b_state', jsonfield.fields.JSONField(default=dict)),
                ('date', models.DateField()),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='api.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
